# config.yaml

setting:
  # 白名单模式：若为 true，则【只】处理 extension_map 里定义的文件，忽略其他所有文件
  # 若为 false，则处理所有文件，未定义的归入 "Others"
  whitelist_mode: false

# ===  黑名单 ===

blacklist:
  extensions:
    - .tmp
    - .bal
    - .ini
    - .ink
  filenames:
    - desktop.ini

# === 扩展名分类映射 ===
extension_map:
  Image:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .webp
    - .svg
    - .psd
    - .raw
  Document:
    - .txt
    - .md
    - .pdf
    - .docx
    - .xlsx
    - .pptx
    - .log
  Audio:
    - .mp3
    - .wav
    - .flac
    - .aac
    - .ogg
    - .m4a
  Video:
    - .mp4
    - .mkv
    - .mov
    - .avi
    - .ts
  Code:
    - .c
    - .cpp
    - .py
    - .java
    - .js
    - .ts
    - .html
  Archive:
    - .zip
    - .rar
    - .7z
    - .gz
  Executable:
    - .exe
    - .msi
    - .bat
    - .sh
    - .dll
    - .jar
  Specialized:
    - .litematic
    - .schem
    - .ttf